//! # `ironaccelerator-rocm`
//!
//! ROCm / HIP backend. Targets the ROCm 6.x API surface and the AMD
//! datacenter accelerator stack:
//!
//! - **HIP** driver + runtime (analogous to CUDA driver/runtime)
//! - **hipBLAS / hipBLASLt** — dense matmul, FP8 on CDNA3+
//! - **MIOpen** — convolution + fused kernels (cuDNN analogue)
//! - **rocFFT, rocRAND, rocSPARSE, rocSOLVER**
//! - **RCCL** — collective comms (NCCL analogue)
//! - **Composable Kernel** — tunable templates (CUTLASS analogue)
//!
//! ## Status
//!
//! v0.1 scaffold: backend trait wired up, dynamic-loading probe in place.
//! HIP FFI bindings will be generated by `bindings_generator` (mirroring the
//! cudarc crate layout). The CDNA3 (`gfx942`) FP8 path through hipBLASLt is
//! the highest-priority follow-up.

#![allow(
    clippy::missing_safety_doc,
    clippy::too_many_arguments,
    clippy::type_complexity
)]

pub mod backend;
pub mod blas;
pub mod drv;

pub use backend::{RocmBackend, ROCM_BACKEND};

pub fn register(reg: &mut ironaccelerator_core::BackendRegistry) {
    // Force the Lazy and hand the registry the inner `'static` reference.
    let b: &'static backend::RocmBackend = &ROCM_BACKEND;
    reg.register(b);
}
