//! Cross-cutting optimisations referenced by strategies.

use crate::{Id, Ontology, Optimization};

fn op(id: &str, desc: &str, savings: &str, requires: &[&str]) -> Optimization {
    Optimization {
        id: Id(id.into()),
        description: desc.into(),
        savings: savings.into(),
        requires: requires.iter().map(|s| s.to_string()).collect(),
    }
}

pub fn populate(o: &mut Ontology) {
    let xs = [
        op("opt.fp8_recipe",
           "Per-tensor delayed-scaling FP8 with FP32 accumulate.",
           "~2x throughput, ~1.7x memory vs BF16",
           &["FP8_E4M3", "TENSOR_CORES"]),
        op("opt.epilogue_fusion",
           "Fuse bias add, activation, residual into matmul epilogue.",
           "Removes 1-2 element-wise passes",
           &[]),
        op("opt.softmax_online",
           "Single-pass online softmax (numerically stable, no rematerialisation).",
           "Removes one pass over QK^T",
           &[]),
        op("opt.warp_specialization",
           "Producer/consumer warp partitioning with async copies.",
           "Hides shared-memory latency",
           &["sm_90"]),
        op("opt.kv_paging",
           "Paged KV-cache: physical block table + virtual block table.",
           "~5x serving throughput at high batch",
           &[]),
        op("opt.continuous_batching",
           "In-flight request batching at the iteration level.",
           "~2-3x throughput vs static batching",
           &[]),
        op("opt.in_flight_batching",
           "TensorRT-LLM IFB scheduler.", "Same as continuous batching", &[]),
        op("opt.tensor_cores",
           "Use the architecture's MMA / matrix-core instructions directly.",
           "10-20x vs CUDA cores", &["TENSOR_CORES"]),
        op("opt.swizzle",
           "Shared-memory swizzling pattern to avoid bank conflicts.",
           "Eliminates ~4-way bank conflicts", &[]),
        op("opt.autotune",
           "Cache-keyed runtime selection over a kernel grid.",
           "Workload-dependent (5-50%)", &[]),
        op("opt.heuristic_search",
           "cuDNN-style ahead-of-time heuristic + benchmark engine cache.",
           "Picks near-optimal kernel without user tuning", &[]),
        op("opt.unified_memory",
           "Use Apple's unified memory model — no host↔device copy.",
           "Eliminates PCIe-equivalent traffic", &["UNIFIED_MEMORY"]),
        op("opt.ane_offload",
           "Offload sub-graphs to the Apple Neural Engine via CoreML.",
           "10-30x perf-per-watt for compatible ops", &["ANE"]),
        op("opt.hmx_offload",
           "Place matmul on Hexagon HMX accelerator.",
           "Order-of-magnitude vs HVX-only path", &["HMX"]),
        op("opt.int8_quant",
           "Symmetric per-channel weight + per-tensor activation quant.",
           "~4x memory, ~2x throughput", &["INT8"]),
        op("opt.sparsity_2_4",
           "Structured 2:4 sparsity with vendor sparse Tensor-Core path.",
           "~2x throughput on sparse weights", &["SPARSE_2_4"]),
        op("opt.ring_collective",
           "Ring all-reduce — bandwidth-optimal for large messages.",
           "Hits the link bandwidth ceiling on N≥4 ranks", &[]),
        op("opt.tree_collective",
           "Tree all-reduce — latency-optimal for small messages.",
           "Beats ring below ~16 KiB", &[]),
        op("opt.block_sparse",
           "Block-sparse expert FFN — keeps the matmul dense per active expert.",
           "Recovers most of the speedup MoE *should* give", &[]),
        op("opt.expert_parallel",
           "Place experts on different ranks; route via all-to-all.",
           "Scales MoE training past one node", &[]),
        op("opt.coalesced_gather",
           "Warp-strided gather pattern for embedding lookups.",
           "Saturates HBM with high-cardinality vocabularies", &[]),
        op("opt.elementwise_fusion",
           "Fuse a chain of element-wise ops into the producer kernel.",
           "Removes 1 HBM round-trip per fused op", &[]),
        op("opt.philox_rng",
           "Philox counter-based RNG — stateless, vectorisable.",
           "RNG cost becomes negligible inside the dropout kernel", &[]),
        op("opt.fft_plan_cache",
           "Cache `cufftHandle` per (size, batch, dtype).",
           "Removes ~ms-scale plan creation from steady-state",  &[]),
    ];

    for x in xs {
        o.optimizations.insert(x.id.clone(), x);
    }
}
