//! Strategy sub-graph — the *how* for each (workload, hardware) pair.

use crate::{Id, Ontology, StrategyClass};
use ironaccelerator_core::BackendKind;
use std::collections::HashMap;

fn s(
    id: &str,
    library: &str,
    backends: &[BackendKind],
    min_arch: &[(BackendKind, &str)],
    workloads: &[&str],
    optimizations: &[&str],
    desc: &str,
    rationale: &str,
    jit: bool,
    open: bool,
) -> StrategyClass {
    let mut ma = HashMap::new();
    for (b, a) in min_arch {
        ma.insert(b.name().to_string(), a.to_string());
    }
    StrategyClass {
        id: Id(id.into()),
        library: library.into(),
        backends: backends.to_vec(),
        min_arch: ma,
        workloads: workloads.iter().map(|w| Id((*w).into())).collect(),
        optimizations: optimizations.iter().map(|o| Id((*o).into())).collect(),
        description: desc.into(),
        rationale: rationale.into(),
        jit,
        open_source: open,
    }
}

pub fn populate(o: &mut Ontology) {
    use BackendKind::*;
    let xs = [
        // ── CUDA / NVIDIA ────────────────────────────────────────────────
        s("strategy.cublaslt.fp8_te",
          "cublasLt",
          &[Cuda],
          &[(Cuda, "sm_90")],
          &["workload.gemm", "workload.batched_gemm"],
          &["opt.fp8_recipe", "opt.epilogue_fusion"],
          "cuBLASLt FP8 GEMM with Transformer-Engine recipe and fused epilogue.",
          "Hopper+ FP8 path. Highest TFLOPS for LLM linear layers; epilogue fuses bias+activation.",
          false, false),
        s("strategy.cublaslt.bf16",
          "cublasLt", &[Cuda], &[(Cuda, "sm_80")],
          &["workload.gemm", "workload.batched_gemm"],
          &["opt.epilogue_fusion"],
          "cuBLASLt BF16 GEMM with epilogue fusion.",
          "Best general-purpose dense matmul on Ampere+; portable across SKUs.",
          false, false),
        s("strategy.cutlass.tile",
          "cutlass", &[Cuda], &[(Cuda, "sm_70")],
          &["workload.gemm", "workload.conv2d"],
          &["opt.tensor_cores", "opt.swizzle"],
          "Hand-tuned CUTLASS template instantiation (specific tile + stages).",
          "Outperforms cuBLAS on irregular shapes and when fusing custom epilogues.",
          true, true),
        s("strategy.flashattn.v3",
          "flash-attention", &[Cuda], &[(Cuda, "sm_90")],
          &["workload.flash_attention", "workload.attention"],
          &["opt.softmax_online", "opt.warp_specialization", "opt.fp8_recipe"],
          "FlashAttention-3: warp-specialised, async, FP8 on Hopper.",
          "State-of-the-art attention on Hopper. ~2x FA-2 throughput at long contexts.",
          true, true),
        s("strategy.flashattn.v2",
          "flash-attention", &[Cuda, Rocm], &[(Cuda, "sm_80"), (Rocm, "gfx90a")],
          &["workload.flash_attention", "workload.attention"],
          &["opt.softmax_online"],
          "FlashAttention-2 (portable).",
          "Default fused-attention path for Ampere and CDNA2.", true, true),
        s("strategy.vllm.paged",
          "vllm", &[Cuda, Rocm], &[(Cuda, "sm_80"), (Rocm, "gfx90a")],
          &["workload.paged_attention"],
          &["opt.kv_paging", "opt.continuous_batching"],
          "vLLM PagedAttention kernel + KV-cache page manager.",
          "Required path for high-throughput LLM serving with dynamic batches.",
          false, true),
        s("strategy.cudnn.flash",
          "cudnn", &[Cuda], &[(Cuda, "sm_80")],
          &["workload.flash_attention", "workload.conv2d"],
          &["opt.softmax_online", "opt.heuristic_search"],
          "cuDNN v9 fused attention / conv with runtime heuristic search.",
          "Closed-source but ships with CUDA; unbeatable on conv workloads.",
          false, false),
        s("strategy.triton.gemm",
          "triton", &[Cuda, Rocm], &[(Cuda, "sm_80"), (Rocm, "gfx90a")],
          &["workload.gemm", "workload.spmm", "workload.elementwise"],
          &["opt.autotune"],
          "Triton-JIT generated kernel with runtime autotuning.",
          "Excellent for novel shapes / fused ops; cold-start cost from JIT.",
          true, true),
        s("strategy.tensorrt_llm.engine",
          "tensorrt-llm", &[Cuda], &[(Cuda, "sm_80")],
          &["workload.flash_attention", "workload.gemm"],
          &["opt.fp8_recipe", "opt.in_flight_batching"],
          "TensorRT-LLM compiled engine.",
          "Best end-to-end LLM serving latency on NVIDIA when graph is static.",
          false, false),

        // ── ROCm / AMD ───────────────────────────────────────────────────
        s("strategy.hipblaslt.fp8",
          "hipBLASLt", &[Rocm], &[(Rocm, "gfx942")],
          &["workload.gemm", "workload.batched_gemm"],
          &["opt.fp8_recipe", "opt.epilogue_fusion"],
          "hipBLASLt FP8 GEMM (CDNA3+).",
          "AMD FP8 path on MI300; matches cuBLASLt design.", false, false),
        s("strategy.composable_kernel.gemm",
          "composable-kernel", &[Rocm], &[(Rocm, "gfx908")],
          &["workload.gemm", "workload.flash_attention"],
          &["opt.tensor_cores"],
          "AMD Composable Kernel template (CK).",
          "Tunable templates akin to CUTLASS; primary route for fused kernels on ROCm.",
          true, true),
        s("strategy.rocblas.bf16",
          "rocBLAS", &[Rocm], &[(Rocm, "gfx908")],
          &["workload.gemm"],
          &[],
          "rocBLAS BF16/FP16 GEMM.",
          "Stable default on all ROCm devices.", false, true),

        // ── Metal / Apple ────────────────────────────────────────────────
        s("strategy.mps.matmul",
          "mps", &[Metal], &[(Metal, "Apple7")],
          &["workload.gemm", "workload.gemv"],
          &["opt.unified_memory"],
          "MPSMatrixMultiplication.",
          "Default Apple GEMM; well-tuned, no JIT.", false, false),
        s("strategy.mlx.attention",
          "mlx", &[Metal], &[(Metal, "Apple8")],
          &["workload.flash_attention", "workload.attention"],
          &["opt.unified_memory", "opt.softmax_online"],
          "MLX fused attention kernel.",
          "Apple-native fused attention; uses unified memory effectively.",
          false, true),
        s("strategy.coreml.ane",
          "coreml", &[Metal], &[(Metal, "Apple7")],
          &["workload.gemm", "workload.conv2d", "workload.flash_attention"],
          &["opt.ane_offload"],
          "CoreML compiled model offloading to ANE when possible.",
          "Best perf-per-watt on Apple silicon; falls back to GPU/CPU per op.",
          false, false),

        // ── QNN / Qualcomm ───────────────────────────────────────────────
        s("strategy.qnn.htp_int8",
          "qnn-htp", &[QualcommNpu], &[(QualcommNpu, "v68")],
          &["workload.gemm", "workload.conv2d", "workload.attention"],
          &["opt.hmx_offload", "opt.int8_quant"],
          "QNN Hexagon HTP graph in INT8.",
          "Highest perf-per-watt on Snapdragon for quantised inference.",
          false, false),
        s("strategy.qnn.htp_fp16",
          "qnn-htp", &[QualcommNpu], &[(QualcommNpu, "v73")],
          &["workload.gemm", "workload.attention"],
          &["opt.hmx_offload"],
          "QNN HTP FP16.",
          "Used when calibration data isn't available for INT8.", false, false),

        // ── Collective comms ────────────────────────────────────────────
        s("strategy.nccl.allreduce",
          "nccl", &[Cuda], &[(Cuda, "sm_60")],
          &["workload.allreduce", "workload.allgather", "workload.reducescatter"],
          &["opt.ring_collective", "opt.tree_collective"],
          "NCCL all-reduce / all-gather / reduce-scatter (ring + tree).",
          "De-facto NVIDIA collective; auto-tunes ring vs tree by message size.",
          false, true),
        s("strategy.rccl.allreduce",
          "rccl", &[Rocm], &[(Rocm, "gfx908")],
          &["workload.allreduce", "workload.allgather", "workload.reducescatter"],
          &["opt.ring_collective"],
          "RCCL — ROCm port of NCCL.",
          "Standard collective path on AMD; mostly drop-in replacement for NCCL.",
          false, true),

        // ── MoE ─────────────────────────────────────────────────────────
        s("strategy.megablocks.moe",
          "megablocks", &[Cuda, Rocm], &[(Cuda, "sm_80"), (Rocm, "gfx942")],
          &["workload.moe_dispatch", "workload.moe_combine"],
          &["opt.block_sparse"],
          "MegaBlocks block-sparse MoE kernels.",
          "Avoids the load-imbalance pathologies of dense MoE; SOTA on Ampere+.",
          true, true),
        s("strategy.deepspeed.moe",
          "deepspeed-moe", &[Cuda], &[(Cuda, "sm_70")],
          &["workload.moe_dispatch", "workload.moe_combine"],
          &["opt.expert_parallel"],
          "DeepSpeed-MoE expert-parallel dispatch.",
          "Pairs naturally with DeepSpeed ZeRO + tensor parallelism.",
          false, true),

        // ── Embeddings ──────────────────────────────────────────────────
        s("strategy.cuda.embedding_gather",
          "ironaccelerator-cuda", &[Cuda], &[(Cuda, "sm_70")],
          &["workload.embedding", "workload.embedding_bag"],
          &["opt.coalesced_gather"],
          "Coalesced gather kernel (warp-strided).",
          "Memory-bound; coalesced-load is the only knob that matters.",
          false, true),

        // ── Rotary / Dropout ────────────────────────────────────────────
        s("strategy.cuda.rope_fused",
          "ironaccelerator-cuda", &[Cuda, Rocm], &[(Cuda, "sm_75"), (Rocm, "gfx908")],
          &["workload.rotary"],
          &["opt.elementwise_fusion"],
          "Fused RoPE that interleaves sin/cos with the QK projection.",
          "Removes a full HBM round-trip vs. separate RoPE pass.",
          false, true),
        s("strategy.cuda.dropout_fused",
          "ironaccelerator-cuda", &[Cuda, Rocm], &[(Cuda, "sm_70"), (Rocm, "gfx908")],
          &["workload.dropout"],
          &["opt.elementwise_fusion", "opt.philox_rng"],
          "Philox-RNG dropout fused into preceding activation.",
          "Removes the dropout HBM pass during training.",
          false, true),

        // ── FFT (extra) ─────────────────────────────────────────────────
        s("strategy.cufft.multi",
          "cufft", &[Cuda], &[(Cuda, "sm_70")],
          &["workload.fft"],
          &["opt.fft_plan_cache"],
          "cuFFT multi-plan with cached descriptor.",
          "Plan creation dominates first-call cost; cache it process-wide.",
          false, false),

        // ── Reference ────────────────────────────────────────────────────
        s("strategy.reference.naive",
          "ironaccelerator-cpu", &[Cpu],
          &[(Cpu, "any")],
          &["workload.gemm", "workload.gemv", "workload.softmax",
            "workload.elementwise", "workload.layernorm", "workload.rmsnorm"],
          &[],
          "Naive CPU reference implementation.",
          "Correctness oracle; never the perf choice.", false, true),
    ];

    for x in xs {
        o.strategies.insert(x.id.clone(), x);
    }
}
