//! Strategy sub-graph — the *how* for each (workload, hardware) pair.

use crate::{Id, Ontology, StrategyClass};
use ironaccelerator_core::workload::Phase;
use ironaccelerator_core::{BackendKind, DType};
use std::collections::HashMap;

#[allow(clippy::too_many_arguments)]
fn s(
    id: &str,
    library: &str,
    backends: &[BackendKind],
    min_arch: &[(BackendKind, &str)],
    workloads: &[&str],
    optimizations: &[&str],
    dtypes: &[DType],
    phases: &[Phase],
    desc: &str,
    rationale: &str,
    jit: bool,
    open: bool,
) -> StrategyClass {
    let mut ma = HashMap::new();
    for (b, a) in min_arch {
        ma.insert(b.name().to_string(), a.to_string());
    }
    StrategyClass {
        id: Id(id.into()),
        library: library.into(),
        backends: backends.to_vec(),
        min_arch: ma,
        workloads: workloads.iter().map(|w| Id((*w).into())).collect(),
        optimizations: optimizations.iter().map(|o| Id((*o).into())).collect(),
        supported_dtypes: dtypes.to_vec(),
        supported_phases: phases.to_vec(),
        description: desc.into(),
        rationale: rationale.into(),
        jit,
        open_source: open,
    }
}

// Common dtype/phase shortcuts.
const FP8: &[DType] = &[DType::F8E4M3, DType::F8E5M2];
const FP16_BF16: &[DType] = &[DType::F16, DType::Bf16];
const FP16_BF16_F32: &[DType] = &[DType::F16, DType::Bf16, DType::F32];
const INT8: &[DType] = &[DType::I8];
const FP16_INT8: &[DType] = &[DType::F16, DType::I8];
const INFER: &[Phase] = &[Phase::Inference];
const TRAIN_INFER: &[Phase] = &[Phase::Training, Phase::Inference];
const ANY_PHASE: &[Phase] = &[];

pub fn populate(o: &mut Ontology) {
    use BackendKind::*;
    let xs = [
        // ── CUDA / NVIDIA ────────────────────────────────────────────────
        s("strategy.cublaslt.fp8_te",
          "cublasLt", &[Cuda], &[(Cuda, "sm_90")],
          &["workload.gemm", "workload.batched_gemm"],
          &["opt.fp8_recipe", "opt.epilogue_fusion"],
          FP8, INFER,
          "cuBLASLt FP8 GEMM with Transformer-Engine recipe and fused epilogue.",
          "Hopper+ FP8 path. Highest TFLOPS for LLM linear layers; epilogue fuses bias+activation.",
          false, false),
        s("strategy.cublaslt.bf16",
          "cublasLt", &[Cuda], &[(Cuda, "sm_80")],
          &["workload.gemm", "workload.batched_gemm"],
          &["opt.epilogue_fusion"],
          FP16_BF16, TRAIN_INFER,
          "cuBLASLt BF16 GEMM with epilogue fusion.",
          "Best general-purpose dense matmul on Ampere+; portable across SKUs.",
          false, false),
        s("strategy.cutlass.tile",
          "cutlass", &[Cuda], &[(Cuda, "sm_70")],
          &["workload.gemm", "workload.conv2d"],
          &["opt.tensor_cores", "opt.swizzle"],
          FP16_BF16_F32, TRAIN_INFER,
          "Hand-tuned CUTLASS template instantiation (specific tile + stages).",
          "Outperforms cuBLAS on irregular shapes and when fusing custom epilogues.",
          true, true),
        s("strategy.flashattn.v3",
          "flash-attention", &[Cuda], &[(Cuda, "sm_90")],
          &["workload.flash_attention", "workload.attention"],
          &["opt.softmax_online", "opt.warp_specialization", "opt.fp8_recipe"],
          &[DType::F16, DType::Bf16, DType::F8E4M3], INFER,
          "FlashAttention-3: warp-specialised, async, FP8 on Hopper.",
          "State-of-the-art attention on Hopper. ~2x FA-2 throughput at long contexts.",
          true, true),
        s("strategy.flashattn.v2",
          "flash-attention", &[Cuda, Rocm], &[(Cuda, "sm_80"), (Rocm, "gfx90a")],
          &["workload.flash_attention", "workload.attention"],
          &["opt.softmax_online"],
          FP16_BF16, TRAIN_INFER,
          "FlashAttention-2 (portable).",
          "Default fused-attention path for Ampere and CDNA2.", true, true),
        s("strategy.vllm.paged",
          "vllm", &[Cuda, Rocm], &[(Cuda, "sm_80"), (Rocm, "gfx90a")],
          &["workload.paged_attention"],
          &["opt.kv_paging", "opt.continuous_batching"],
          FP16_BF16, INFER,
          "vLLM PagedAttention kernel + KV-cache page manager.",
          "Required path for high-throughput LLM serving with dynamic batches.",
          false, true),
        s("strategy.cudnn.flash",
          "cudnn", &[Cuda], &[(Cuda, "sm_80")],
          &["workload.flash_attention", "workload.conv2d"],
          &["opt.softmax_online", "opt.heuristic_search"],
          FP16_BF16, TRAIN_INFER,
          "cuDNN v9 fused attention / conv with runtime heuristic search.",
          "Closed-source but ships with CUDA; unbeatable on conv workloads.",
          false, false),
        s("strategy.triton.gemm",
          "triton", &[Cuda, Rocm], &[(Cuda, "sm_80"), (Rocm, "gfx90a")],
          &["workload.gemm", "workload.spmm", "workload.elementwise"],
          &["opt.autotune"],
          FP16_BF16_F32, TRAIN_INFER,
          "Triton-JIT generated kernel with runtime autotuning.",
          "Excellent for novel shapes / fused ops; cold-start cost from JIT.",
          true, true),
        s("strategy.tensorrt_llm.engine",
          "tensorrt-llm", &[Cuda], &[(Cuda, "sm_80")],
          &["workload.flash_attention", "workload.gemm"],
          &["opt.fp8_recipe", "opt.in_flight_batching"],
          &[DType::F16, DType::Bf16, DType::F8E4M3], INFER,
          "TensorRT-LLM compiled engine.",
          "Best end-to-end LLM serving latency on NVIDIA when graph is static.",
          false, false),
        s("strategy.ironaccelerator.flash_moe",
          "ironaccelerator-cuda", &[Cuda], &[(Cuda, "sm_80")],
          &["workload.moe_dispatch", "workload.moe_combine",
            "workload.gemm", "workload.activation"],
          &["opt.fp8_recipe", "opt.softmax_online", "opt.elementwise_fusion"],
          FP16_BF16, INFER,
          "In-crate Flash MoE forward pass (router→permute→expert GEMMs→combine).",
          "First-party MoE path verified live on Ampere; FP16 + BF16 supported.",
          true, true),

        // ── ROCm / AMD ───────────────────────────────────────────────────
        s("strategy.hipblaslt.fp8",
          "hipBLASLt", &[Rocm], &[(Rocm, "gfx942")],
          &["workload.gemm", "workload.batched_gemm"],
          &["opt.fp8_recipe", "opt.epilogue_fusion"],
          FP8, INFER,
          "hipBLASLt FP8 GEMM (CDNA3+).",
          "AMD FP8 path on MI300; matches cuBLASLt design.", false, false),
        s("strategy.composable_kernel.gemm",
          "composable-kernel", &[Rocm], &[(Rocm, "gfx908")],
          &["workload.gemm", "workload.flash_attention"],
          &["opt.tensor_cores"],
          FP16_BF16_F32, TRAIN_INFER,
          "AMD Composable Kernel template (CK).",
          "Tunable templates akin to CUTLASS; primary route for fused kernels on ROCm.",
          true, true),
        s("strategy.rocblas.bf16",
          "rocBLAS", &[Rocm], &[(Rocm, "gfx908")],
          &["workload.gemm"], &[],
          FP16_BF16, TRAIN_INFER,
          "rocBLAS BF16/FP16 GEMM.",
          "Stable default on all ROCm devices.", false, true),

        // ── Metal / Apple ────────────────────────────────────────────────
        s("strategy.mps.matmul",
          "mps", &[Metal], &[(Metal, "Apple7")],
          &["workload.gemm", "workload.gemv"],
          &["opt.unified_memory"],
          FP16_BF16_F32, TRAIN_INFER,
          "MPSMatrixMultiplication.",
          "Default Apple GEMM; well-tuned, no JIT.", false, false),
        s("strategy.mlx.attention",
          "mlx", &[Metal], &[(Metal, "Apple8")],
          &["workload.flash_attention", "workload.attention"],
          &["opt.unified_memory", "opt.softmax_online"],
          FP16_BF16, TRAIN_INFER,
          "MLX fused attention kernel.",
          "Apple-native fused attention; uses unified memory effectively.",
          false, true),
        s("strategy.coreml.ane",
          "coreml", &[Metal], &[(Metal, "Apple7")],
          &["workload.gemm", "workload.conv2d", "workload.flash_attention"],
          &["opt.ane_offload"],
          FP16_INT8, INFER,
          "CoreML compiled model offloading to ANE when possible.",
          "Best perf-per-watt on Apple silicon; falls back to GPU/CPU per op.",
          false, false),

        // ── QNN / Qualcomm ───────────────────────────────────────────────
        s("strategy.qnn.htp_int8",
          "qnn-htp", &[QualcommNpu], &[(QualcommNpu, "v68")],
          &["workload.gemm", "workload.conv2d", "workload.attention"],
          &["opt.hmx_offload", "opt.int8_quant"],
          INT8, INFER,
          "QNN Hexagon HTP graph in INT8.",
          "Highest perf-per-watt on Snapdragon for quantised inference.",
          false, false),
        s("strategy.qnn.htp_fp16",
          "qnn-htp", &[QualcommNpu], &[(QualcommNpu, "v73")],
          &["workload.gemm", "workload.attention"],
          &["opt.hmx_offload"],
          &[DType::F16], INFER,
          "QNN HTP FP16.",
          "Used when calibration data isn't available for INT8.", false, false),

        // ── Vulkan / OpenGL / WebGPU (portable cross-vendor) ─────────────
        s("strategy.vulkan.compute",
          "ironaccelerator-vulkan", &[Vulkan], &[(Vulkan, "1.3")],
          &["workload.gemm", "workload.elementwise", "workload.softmax",
            "workload.layernorm", "workload.activation"],
          &["opt.elementwise_fusion"],
          FP16_BF16_F32, INFER,
          "SPIR-V compute shaders over Vulkan 1.3.",
          "Portable fallback when no first-class backend is available.",
          false, true),
        s("strategy.opengl.compute",
          "ironaccelerator-opengl", &[OpenGl], &[(OpenGl, "4.3")],
          &["workload.gemm", "workload.elementwise"],
          &[],
          &[DType::F32, DType::F16], INFER,
          "OpenGL 4.3 compute shaders.",
          "Legacy fallback; use only when Vulkan/WebGPU aren't available.",
          false, true),
        s("strategy.webgpu.wgsl",
          "ironaccelerator-webgpu", &[WebGpu], &[(WebGpu, "1.0")],
          &["workload.gemm", "workload.elementwise", "workload.softmax"],
          &["opt.elementwise_fusion"],
          &[DType::F32, DType::F16], INFER,
          "WGSL compute shaders through wgpu / browser WebGPU.",
          "Primary path for Rust→WASM in-browser acceleration.",
          false, true),

        // ── Intel Level Zero ────────────────────────────────────────────
        s("strategy.levelzero.xe_gemm",
          "ironaccelerator-levelzero", &[LevelZero], &[(LevelZero, "1.3")],
          &["workload.gemm", "workload.batched_gemm", "workload.conv2d"],
          &["opt.tensor_cores"],
          FP16_BF16_F32, TRAIN_INFER,
          "Level-Zero GEMM via Intel Xe Matrix Extensions (XMX).",
          "Preferred path on Intel Arc / Ponte Vecchio / Meteor Lake NPU.",
          false, true),
        s("strategy.levelzero.npu_infer",
          "ironaccelerator-levelzero", &[LevelZero], &[(LevelZero, "1.3")],
          &["workload.conv2d", "workload.attention", "workload.gemm"],
          &["opt.int8_quant"],
          FP16_INT8, INFER,
          "Intel NPU graph compile + submit (OpenVINO-style).",
          "Low-power inference on Core Ultra / Lunar Lake; INT8 preferred.",
          false, true),

        // ── Google TPU (PJRT) ───────────────────────────────────────────
        s("strategy.tpu.pjrt_xla",
          "pjrt", &[Tpu], &[(Tpu, "v4")],
          &["workload.gemm", "workload.batched_gemm", "workload.conv2d",
            "workload.flash_attention", "workload.layernorm", "workload.softmax"],
          &["opt.heuristic_search"],
          &[DType::Bf16, DType::F32, DType::I8], TRAIN_INFER,
          "PJRT plugin bridging XLA-compiled HLO onto TPU MXUs.",
          "Canonical TPU path; XLA's fusion + layout passes drive perf.",
          false, true),
        s("strategy.tpu.pjrt_fp8",
          "pjrt", &[Tpu], &[(Tpu, "v6e")],
          &["workload.gemm", "workload.flash_attention"],
          &["opt.fp8_recipe"],
          FP8, INFER,
          "PJRT FP8 path on TPU v6e.",
          "Trillium's MXU supports FP8; recipe mirrors Hopper's TE.",
          false, true),

        // ── AWS Neuron (Trainium / Inferentia) ──────────────────────────
        s("strategy.neuron.compile_graph",
          "libnrt", &[Neuron], &[(Neuron, "trn1")],
          &["workload.gemm", "workload.batched_gemm", "workload.conv2d",
            "workload.flash_attention", "workload.layernorm"],
          &["opt.heuristic_search"],
          &[DType::F16, DType::Bf16, DType::F32], TRAIN_INFER,
          "Neuron-compiled NEFF graph executed via the Neuron Runtime.",
          "AOT-compiled graphs; JIT variant exists but NEFF is the fast path.",
          false, false),
        s("strategy.neuron.fp8_infer",
          "libnrt", &[Neuron], &[(Neuron, "trn2")],
          &["workload.gemm", "workload.flash_attention"],
          &["opt.fp8_recipe"],
          FP8, INFER,
          "Trainium 2 FP8 inference path.",
          "FP8 support on Neuron Cores v3; inference-only today.",
          false, false),

        // ── Collective comms ────────────────────────────────────────────
        s("strategy.nccl.allreduce",
          "nccl", &[Cuda], &[(Cuda, "sm_60")],
          &["workload.allreduce", "workload.allgather", "workload.reducescatter"],
          &["opt.ring_collective", "opt.tree_collective"],
          &[], ANY_PHASE,
          "NCCL all-reduce / all-gather / reduce-scatter (ring + tree).",
          "De-facto NVIDIA collective; auto-tunes ring vs tree by message size.",
          false, true),
        s("strategy.rccl.allreduce",
          "rccl", &[Rocm], &[(Rocm, "gfx908")],
          &["workload.allreduce", "workload.allgather", "workload.reducescatter"],
          &["opt.ring_collective"],
          &[], ANY_PHASE,
          "RCCL — ROCm port of NCCL.",
          "Standard collective path on AMD; mostly drop-in replacement for NCCL.",
          false, true),

        // ── MoE ─────────────────────────────────────────────────────────
        s("strategy.megablocks.moe",
          "megablocks", &[Cuda, Rocm], &[(Cuda, "sm_80"), (Rocm, "gfx942")],
          &["workload.moe_dispatch", "workload.moe_combine"],
          &["opt.block_sparse"],
          FP16_BF16, TRAIN_INFER,
          "MegaBlocks block-sparse MoE kernels.",
          "Avoids the load-imbalance pathologies of dense MoE; SOTA on Ampere+.",
          true, true),
        s("strategy.deepspeed.moe",
          "deepspeed-moe", &[Cuda], &[(Cuda, "sm_70")],
          &["workload.moe_dispatch", "workload.moe_combine"],
          &["opt.expert_parallel"],
          FP16_BF16, TRAIN_INFER,
          "DeepSpeed-MoE expert-parallel dispatch.",
          "Pairs naturally with DeepSpeed ZeRO + tensor parallelism.",
          false, true),

        // ── Embeddings ──────────────────────────────────────────────────
        s("strategy.cuda.embedding_gather",
          "ironaccelerator-cuda", &[Cuda], &[(Cuda, "sm_70")],
          &["workload.embedding", "workload.embedding_bag"],
          &["opt.coalesced_gather"],
          &[], ANY_PHASE,
          "Coalesced gather kernel (warp-strided).",
          "Memory-bound; coalesced-load is the only knob that matters.",
          false, true),

        // ── Rotary / Dropout ────────────────────────────────────────────
        s("strategy.cuda.rope_fused",
          "ironaccelerator-cuda", &[Cuda, Rocm], &[(Cuda, "sm_75"), (Rocm, "gfx908")],
          &["workload.rotary"],
          &["opt.elementwise_fusion"],
          FP16_BF16, TRAIN_INFER,
          "Fused RoPE that interleaves sin/cos with the QK projection.",
          "Removes a full HBM round-trip vs. separate RoPE pass.",
          false, true),
        s("strategy.cuda.dropout_fused",
          "ironaccelerator-cuda", &[Cuda, Rocm], &[(Cuda, "sm_70"), (Rocm, "gfx908")],
          &["workload.dropout"],
          &["opt.elementwise_fusion", "opt.philox_rng"],
          FP16_BF16_F32, &[Phase::Training],
          "Philox-RNG dropout fused into preceding activation.",
          "Removes the dropout HBM pass during training.",
          false, true),

        // ── Reductions / Sparse ─────────────────────────────────────────
        s("strategy.cuda.reduce_softmax",
          "ironaccelerator-cuda", &[Cuda, Rocm], &[(Cuda, "sm_70"), (Rocm, "gfx908")],
          &["workload.reduce", "workload.softmax", "workload.layernorm", "workload.rmsnorm"],
          &["opt.softmax_online"],
          FP16_BF16_F32, TRAIN_INFER,
          "Warp-shuffle reductions + online softmax / layer-norm.",
          "Standard memory-bound primitive; fused into attention wherever possible.",
          false, true),
        s("strategy.cusparse.spmm",
          "cusparse", &[Cuda], &[(Cuda, "sm_70")],
          &["workload.spmm", "workload.sddmm"],
          &[],
          FP16_BF16_F32, TRAIN_INFER,
          "cuSPARSE SpMM / SDDMM kernels.",
          "Default sparse-dense path when sparsity structure is irregular.",
          false, false),

        // ── FFT (extra) ─────────────────────────────────────────────────
        s("strategy.cufft.multi",
          "cufft", &[Cuda], &[(Cuda, "sm_70")],
          &["workload.fft"],
          &["opt.fft_plan_cache"],
          &[DType::F32, DType::F64], ANY_PHASE,
          "cuFFT multi-plan with cached descriptor.",
          "Plan creation dominates first-call cost; cache it process-wide.",
          false, false),

        // ── Reference ────────────────────────────────────────────────────
        s("strategy.reference.naive",
          "ironaccelerator-cpu", &[Cpu],
          &[(Cpu, "any")],
          &["workload.gemm", "workload.gemv", "workload.softmax",
            "workload.elementwise", "workload.layernorm", "workload.rmsnorm",
            "workload.reduce"],
          &[],
          &[], ANY_PHASE,
          "Naive CPU reference implementation.",
          "Correctness oracle; never the perf choice.", false, true),
    ];

    for x in xs {
        o.strategies.insert(x.id.clone(), x);
    }
}
